### ISSUE TITLE
More training = much worse results?

### ISSUE THREAD

**Issue by xjcl** [spro/char-rnn.pytorch#15]
I'm impressed with how you can get reasonable results with this after just a few minutes. However I tried running it overnight with 3 layers and 20'000 iterations and while it did produce reasonable results at around iteration 6'000, it sounds completely delirious by 20'000. It seems to forget nearly all the English words it learned. What is causing this and how can I train the RNN for a long time? For context, these are Discord messages.

     29%|███████████████████████████▎                                                                  | 5799/20000 [53:21<2:10:13,  1.82it/s][53m 21s (5800 28%) 0.6450]
    What's come out the trade in the next to the script to prompts
    If you don't need to use a game audiosu 

     29%|███████████████████████████▋                                                                  | 5899/20000 [54:17<2:12:16,  1.78it/s][54m 17s (5900 29%) 0.5536]
    WhIY
    i saw, the game called "lood ovonit my thing
    Ok
    Oh
    Ok
    Oh
    Ok
    Oh
    Ok
    Oh
    Ok then
    cool
    work
    i wanna st 

     30%|████████████████████████████▏                                                                 | 5999/20000 [55:12<2:10:21,  1.79it/s][55m 13s (6000 30%) 0.4223]
    Whly played with questions then they me called but idk how to cot just trying to do on find it has spi 

     30%|████████████████████████████▋                                                                 | 6099/20000 [56:07<2:07:40,  1.81it/s][56m 8s (6100 30%) 0.3389]
    WhIM.got out
    I'm trying to 10%s I pins to stream it I'll little pretty becanee or my skin "mallice I h 

     31%|█████████████████████████████▏                                                                | 6199/20000 [57:02<2:06:02,  1.82it/s][57m 3s (6200 31%) 0.3418]
    Whaugting game if I didn't beek will know how to down don't need to do
    no
    Oh I don't think you're sent 

     31%|█████████████████████████████▌                                                                | 6299/20000 [57:57<2:04:52,  1.83it/s][57m 58s (6300 31%) 0.3389]
    Why
    I know what the video tomeoming in the Games and I fool if I didn't really have my own music and s 

     32%|██████████████████████████████                                                                | 6399/20000 [58:54<2:04:41,  1.82it/s][58m 54s (6400 32%) 0.3517]
    Whe
    No
    I have to moderate the next song., it's not episony
    https://www.reddit.com/r/osugame/KIIGhdqdqq 

Later:

     96%|█████████████████████████████████████████████████████████████████████████████████████████▋   | 19299/20000 [2:48:01<05:44,  2.03it/s][168m 1s (19300 96%) 2.2831]
    Wh
    Yeah
    Wo ieed mocer abe intoted I hacon itle sonas lyt abr the mevuh soreahmlo hartute ind moru play 

     97%|██████████████████████████████████████████████████████████████████████████████████████████▏  | 19399/20000 [2:48:50<04:52,  2.05it/s][168m 50s (19400 97%) 2.2745]
    Whttackeohhem
    1imese s ting cave need you oade el, ailikh I foeanalytte ofme are oatc brd tanong on an 

     97%|██████████████████████████████████████████████████████████████████████████████████████████▋  | 19499/20000 [2:49:39<04:05,  2.04it/s][169m 39s (19500 97%) 2.2725]
    WhwAaI6K
    I ra5l  lay gor son id doni out thos
    Is $an hhatt
    WO AN* ho I'm mas bery andn ifear he Jrnst  

     98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 19599/20000 [2:50:28<03:16,  2.04it/s][170m 28s (19600 98%) 2.2678]
    Whtts/onoingghhttps://cdn.discordapp.coretent_mentxs gislay
    hoten so
    it's momew
    https://cdn.discordapp 

     98%|███████████████████████████████████████████████████████████████████████████████████████████▌ | 19699/20000 [2:51:17<02:27,  2.04it/s][171m 18s (19700 98%) 2.2421]
    Whatttan. we mma ter
    https://cdn.discordapp.com/attachents/4642861855417395441330/image.png
    the coo to 

     99%|████████████████████████████████████████████████████████████████████████████████████████████ | 19799/20000 [2:52:06<01:38,  2.04it/s][172m 7s (19800 99%) 2.2955]
    Whattttps://youtu.bestcd I whey sciecs wade Nuldr You tan streiill Josne pomen abau dom mre oust vrm s 

     99%|████████████████████████████████████████████████████████████████████████████████████████████▌| 19899/20000 [2:52:55<00:49,  2.04it/s][172m 56s (19900 99%) 2.3319]
    What oooellco
    htts:///waoar.61et
    outhe
    I ners
    An 2MSE DOcSS
    L gand sase lorn
    I doutdae it aanendi
    I'l  

    100%|████████████████████████████████████████████████████████████████████████████████████████████▉| 19999/20000 [2:53:45<00:00,  2.03it/s][173m 45s (20000 100%) 2.3316]
    Wh
    Well 2tre thaettort you hear You
    pue at in lathsch
    It lan thin sine beveresl
    t? muvmes in subd toke

**Comment by thkdlflghlsdghilr** [comment]
I have heard about networks going insane from trying to fine-tune details and failing so much that you get to a point where it only goes downhill. The best fix I have found is adding more layers or just stoping after awhile to prevent the RNN form filling up its memory.

**Comment by spro** [comment]
Yep this is classic overfitting, diminishing returns turned negative returns. @thkdlflghlsdghilr is correct about the potential solutions. I'd guess with a discord dataset you had even worse results because of things like URLs and inconsistent grammar/spelling.
